name: CI

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          node-version-file: .node-version
      - name: Install dependencies
        run: npm ci
      - name: Audit dependencies
        run: npm audit --audit-level=high
      - name: Check formatting
        run: npm run fmt:check
      - name: Check linting
        run: npm run lint:check
      - name: Check types
        run: npm run typecheck
      - name: Run tests
        run: npm run test

  release:
    name: Release?
    needs: [verify]
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Release?
        id: release
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
      - name: Checkout code
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js (NPM)
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: npm ci
      - name: Build
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: npm run build
      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: npm publish --access public
      - name: Setup Node.js (GPR)
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          registry-url: 'https://npm.pkg.github.com'
          scope: '@unfunco'
      - name: Publish to GitHub Packages
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
